<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Thu, 02 Apr 2026 06:05:56 +0000
 */

$conf['title'] = '';
$conf['template'] = 'notes';
$conf['license'] = '0';
$conf['breadcrumbs'] = 0;
$conf['hidepages'] = '(?<=:)datasets$|(?<=:)data$|(?<=:)comments$|(?<=:)sidebar$|(?<=.:)start$|other-matches';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'backlink,register';
$conf['cachetime'] = 0;
$conf['target']['extern'] = '_blank';
$conf['target']['media'] = '_blank';
$conf['target']['windows'] = '_blank';
$conf['notify'] = 'atulgroverr@gmail.com';
$conf['registernotify'] = 'atulgroverr@gmail.com';
$conf['mailfrom'] = 'atulgroverr@gmail.com';
$conf['mailreturnpath'] = 'atulgroverr@gmail.com';
$conf['userewrite'] = '2';
$conf['search_nslimit'] = 2;
$conf['search_fragment'] = 'contains';
$conf['defer_js'] = 0;
$conf['proxy']['user'] = 'admin';
$conf['proxy']['pass'] = '<b>QCNUaGVvMTIzfiFAIw==';
$conf['plugin']['htmlok']['htmlok'] = 1;
$conf['plugin']['htmlok']['phpok'] = 1;
$conf['plugin']['iframe']['js_ok'] = 1;
$conf['plugin']['mermaid']['location'] = 'local';
$conf['plugin']['mermaid']['theme'] = 'default';
$conf['plugin']['mermaid']['look'] = 'classic';
$conf['plugin']['mermaid']['logLevel'] = 'trace';
$conf['plugin']['smtp']['smtp_host'] = '';
$conf['plugin']['move']['minor'] = '0';
$conf['plugin']['move']['autoskip'] = '1';
$conf['plugin']['simplenavi']['peek'] = '3';
$conf['tpl']['retro']['showPageInfo'] = '0';
$conf['tpl']['retro']['topToolBar'] = 'page';
$conf['tpl']['ad-hominem']['darkmode'] = 'disable';
$conf['tpl']['ad-hominem']['navtrail'] = 'link';
$conf['tpl']['ad-hominem']['printstyle'] = 'compact';
$conf['tpl']['ad-hominem']['cookiepos'] = 'hide';
$conf['tpl']['ad-hominem']['langmenu'] = 'tb';
$conf['tpl']['wikipraktik']['wiki'] = '0';
$conf['plugin']['mdpage']['flavor'] = 'markdown-extra';
$conf['htmlok'] = '1';
