# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sat, 12 Apr 2025 06:30:44 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:21232f297a57a5a743894a0e4a801fc3:Atul Grover:admin@resolutionbazaar.com:admin,user