<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Sun, 02 Nov 2025 10:34:28 +0000
 */

$conf['title'] = 'RESOLUTION BAZAAR';
$conf['tagline'] = 'AI AGENTS - INSOLVENCY PROCESSES';
$conf['license'] = '0';
$conf['breadcrumbs'] = 0;
$conf['sneaky_index'] = 1;
$conf['hidepages'] = '(?<=:)sidebar$|(?<=.:)start$|other-matches';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'backlink,recent,revisions,register,subscribe,unsubscribe,source,export_raw';
$conf['subscribers'] = 0;
$conf['target']['extern'] = '_blank';
$conf['userewrite'] = '2';
$conf['proxy']['user'] = 'admin';
$conf['proxy']['pass'] = '<b>QCNUaGVvMTIzfiFAIw==';
$conf['plugin']['aichat']['chatmodel'] = 'OpenAI gpt-3.5-turbo-16k';
$conf['plugin']['aichat']['rephrasemodel'] = 'OpenAI gpt-3.5-turbo-16k';
$conf['plugin']['aichat']['openai_apikey'] = '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';
$conf['plugin']['aichat']['openai_org'] = 'org-QdHETd0tXOfqQ5loAYcXd5cR';
$conf['plugin']['aichat']['chunkSize'] = 300;
$conf['plugin']['aichat']['contextChunks'] = 10;
$conf['plugin']['aichat']['chatHistory'] = 3;
$conf['plugin']['aichat']['rephraseHistory'] = 3;
$conf['plugin']['aichat']['logging'] = 1;
$conf['plugin']['dw2pdf']['showexportbutton'] = 0;
$conf['tpl']['mindthedark']['autoDark'] = '1';
$conf['tpl']['mindthedark']['userChoice'] = '1';
$conf['tpl']['mindthedark']['pluginWrap'] = '1';
$conf['plugin']['twofactor']['optinout'] = 'mandatory';
$conf['plugin']['confightmlok']['use_sure'] = '1';
$conf['plugin']['confightmlok']['use_really_sure'] = '1';
$conf['plugin']['htmlok']['htmlok'] = '1';
$conf['plugin']['iframe']['js_ok'] = '1';
$conf['plugin']['oauth']['singleService'] = '1';
$conf['plugin']['oauth']['register-on-auth'] = '1';
$conf['plugin']['oauth']['overwrite-groups'] = '1';
