# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Fri, 28 Mar 2025 19:37:14 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:21232f297a57a5a743894a0e4a801fc3:Name:resolutionbazaar@gmail.com:admin,user
